Use cairosvg<2 for any python<3
conda-forge/cairosvg-feedstock pull request #23
Opened 2019-09-24 01:39 UTC by MutantPlatypus

Per the CairoSVG change long, support for Python 2 was dropped at
cairosvg==2.0.0.  The last version that supported python2.x was 1.0.22

Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Per #22.
@conda-forge-admin, please rerender

2019-09-24 01:39 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found it was in an excellent condition.

2019-09-24 01:40 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-webservice.

I tried to re-render for you, but it looks like there was nothing to do.

2019-09-24 02:13 UTC, MutantPlatypus commented
It seems the hash check failed when downloading the source from PyPI to the cache? I'm stuck.

2019-09-24 06:52 UTC, carlodri requested changes
You need to manually update the SHA of the package here:

https://github.com/MutantPlatypus/cairosvg-feedstock/blob/4fc304db256cc917225f7d4aff934339ae69362d/recipe/meta.yaml#L10

You can find it here:

https://pypi.org/project/CairoSVG/1.0.22/#copy-hash-modal-ad844210-2b62-4bc0-8931-d4bf5434c4fc

2019-09-25 00:22 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-webservice.

I tried to re-render for you, but it looks like there was nothing to do.

2019-09-25 00:23 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-webservice.

I tried to re-render for you, but it looks like there was nothing to do.

2019-09-25 00:59 UTC, MutantPlatypus commented
Amended the commit, @conda-forge-admin, please rerender.  Let's see if it works.

I couldn't find how to look up the hash on PyPI the way you linked.  It looks like `hashin` could do it too, but I'm curious where you got that URL.

2019-09-25 01:00 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-webservice.

I tried to re-render for you, but it looks like there was nothing to do.

2019-09-25 01:45 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-webservice.

I tried to re-render for you, but it looks like there was nothing to do.

2019-09-25 01:59 UTC, MutantPlatypus commented
All tests seem to be passing, there's just [this warning](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=75130&view=logs&jobId=1bf226d3-0e2f-52d8-fa93-7d9e633347b3&taskId=ec8d466d-e3b4-5115-4f06-222398f91e6c&lineStart=546&lineEnd=547&colStart=1&colEnd=1) about `conda-verify` being unavailable:
````
Importing conda-verify failed.  Please be sure to test your packages.  conda install conda-verify to make this message go away.
WARNING:conda_build.build:Importing conda-verify failed.  Please be sure to test your packages.  conda install conda-verify to make this message go away.
WARNING conda_build.build:bundle_conda(1042): Importing conda-verify failed.  Please be sure to test your packages.  conda install conda-verify to make this message go away.
````
Is this something optional that we can choose to enable in `meta.yml`?  If this would run the tests the [1.0.22 tag](https://github.com/Kozea/CairoSVG/releases/tag/1.0.22), keep in mind that the tag doesn't pass it's own tests.

@conda-forge-admin, please rerender

2019-09-25 02:00 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-webservice.

I tried to re-render for you, but it looks like there was nothing to do.

2019-09-25 02:02 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-webservice.

I tried to re-render for you, but it looks like there was nothing to do.

2019-09-25 02:23 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-webservice.

I tried to re-render for you, but it looks like there was nothing to do.

2019-09-25 03:49 UTC, closed without merging

2019-09-25 03:54 UTC, MutantPlatypus commented
Hi @carlodri, I closed this because of the force pushing and didn't want to blow up your email inbox, there's at least one more problem that should be fixed even though tests are passing, and also have one important question:  CairoSVG has optional dependencies.  I'm not sure if we should include those in the conda dependencies list (to verify it is safe to import them / it is such an old release) or leave them out.  See commits aa7c989 (minimum dependencies) and c8d8e64 (no unused dependencies like `defusedxml` and `pilllow`, added all optional dependencies and use the correct versions for 1.0.22).

2019-09-25 03:58 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-webservice.

I tried to re-render for you, but it looks like there was nothing to do.

2019-09-28 16:53 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-webservice.

I tried to re-render for you, but it looks like there was nothing to do.

2019-09-28 17:27 UTC, MutantPlatypus commented
Per#24, this ready for review

@conda-forge-admin, please rerender